apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:

      labels:
        app: frontend
        env: dev
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
  
  labels:
    app: frontend
    env: dev
  
spec:
  type: LoadBalencer
  selector:
      app: frontend
      env: dev
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP  # Protocol type (default is TCP)

