apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
      env: dev
  template:
    metadata:

      labels:
        app: database
        env: dev
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1
        
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  
  labels:
    app: backend
    env: dev
  
spec:
  type: ClusterIP
  selector:
      app: backend
      env: dev
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP  # Protocol type (default is TCP)

