apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense  # Optional: specify your namespace here
  labels:
    app: backend
    env: dev
spec:
  replicas: 2  # Number of desired pods
  selector:
    matchLabels:
      app: backend
      env: dev
      
  template:
    metadata:
      labels:
        app: backend
        env: dev
    spec:
      containers:
      - name: nginx
        image: joindevops/mysql:v1  # Specify the Docker image
        ports:
        - containerPort: 80  # Port to expose
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense # Optional: specify your namespace here
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer if needed
  selector:
     app: database
     env: dev
  ports:
    - port: 3306  # Port exposed by the service
      targetPort: 3306  # Port on the pod to forward traffic to
